import { Type } from "@google/genai";

export interface MenuItem {
  id: string;
  name: string;
  nameEn?: string;
  price: string;
  description?: string;
  descriptionEn?: string;
  ingredients?: string[];
  ingredientsEn?: string[];
  history?: string;
  historyEn?: string;
  tags?: string[];
  tagsEn?: string[];
  image?: string;
  video?: string;
  category?: string;
}

export interface DrinkCategory {
  name: string;
  nameEn?: string;
  items: MenuItem[];
}

export const COCKTAILS: MenuItem[] = [
  {
    id: "basajaun",
    name: "BASAJAUN",
    nameEn: "BASAJAUN",
    price: "15€",
    description: "Gin Malfy, St Germain, Txakoli.",
    descriptionEn: "Gin Malfy, St Germain, Txakoli.",
    ingredients: ["Gin Malfy", "St Germain", "Txakoli"],
    ingredientsEn: ["Gin Malfy", "St Germain", "Txakoli"],
    history: "Inspirado en el señor del bosque de la mitología vasca, este cóctel combina la frescura del Txakoli con toques florales.",
    historyEn: "Inspired by the lord of the forest from Basque mythology, this cocktail combines the freshness of Txakoli with floral touches.",
    tags: ["Con Alcohol", "Floral", "Vasco"],
    tagsEn: ["With Alcohol", "Floral", "Basque"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771890612/IMG_7097_bdurop.jpg",
    video: "https://res.cloudinary.com/daw44qmzv/video/upload/v1771841209/Agent_video_Pippit_20260223095324_nc4ksx.mp4",
    category: "CON ALCOHOL"
  },
  {
    id: "pepino-dream",
    name: "PEPINO DREAM",
    nameEn: "PEPINO DREAM",
    price: "15€",
    description: "Martini Ambrato, St Germain, Pepino.",
    descriptionEn: "Martini Ambrato, St Germain, Cucumber.",
    ingredients: ["Martini Ambrato", "St Germain", "Pepino"],
    ingredientsEn: ["Martini Ambrato", "St Germain", "Cucumber"],
    history: "Una explosión de frescura verde, ideal para las tardes calurosas en la terraza.",
    historyEn: "An explosion of green freshness, ideal for hot afternoons on the terrace.",
    tags: ["Con Alcohol", "Fresco", "Verde"],
    tagsEn: ["With Alcohol", "Fresh", "Green"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1770995305/IMG_7096_2_i0lyzy.jpg",
    video: "https://res.cloudinary.com/daw44qmzv/video/upload/v1771849492/copy_180F3F6B-9802-49E2-93A0-EC364D99C2EA_ppl0r3.mov",
    category: "CON ALCOHOL"
  },
  {
    id: "strawberry-mule",
    name: "STRAWBERRY MULE",
    nameEn: "STRAWBERRY MULE",
    price: "15€",
    description: "Absolut Elyx, Arándanos, Ginger Beer.",
    descriptionEn: "Absolut Elyx, Blueberries, Ginger Beer.",
    ingredients: ["Absolut Elyx", "Arándanos", "Ginger Beer"],
    ingredientsEn: ["Absolut Elyx", "Blueberries", "Ginger Beer"],
    history: "Una variante afrutada del clásico Moscow Mule con el toque premium de Absolut Elyx.",
    historyEn: "A fruity variant of the classic Moscow Mule with the premium touch of Absolut Elyx.",
    tags: ["Con Alcohol", "Afrutado", "Picante"],
    tagsEn: ["With Alcohol", "Fruity", "Spicy"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771890611/IMG_7113_lsikxh.jpg",
    category: "CON ALCOHOL"
  },
  {
    id: "brandy-cooler",
    name: "BRANDY COOLER",
    nameEn: "BRANDY COOLER",
    price: "15€",
    description: "Brandy, limón, ginger ale.",
    descriptionEn: "Brandy, lemon, ginger ale.",
    ingredients: ["Brandy", "Limón", "Ginger Ale"],
    ingredientsEn: ["Brandy", "Lemon", "Ginger Ale"],
    history: "Un clásico refrescante que resalta las notas cálidas del brandy con el toque chispeante del jengibre.",
    historyEn: "A refreshing classic that highlights the warm notes of brandy with the sparkling touch of ginger.",
    tags: ["Con Alcohol", "Clásico", "Refrescante"],
    tagsEn: ["With Alcohol", "Classic", "Refreshing"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771026961/IMG_7100_vphp4b.jpg",
    category: "CON ALCOHOL"
  },
  {
    id: "hor-dago",
    name: "HOR DAGO!!",
    nameEn: "HOR DAGO!!",
    price: "15€",
    description: "Patxarán, café, humo.",
    descriptionEn: "Patxarán, coffee, smoke.",
    ingredients: ["Patxarán", "Café", "Humo"],
    ingredientsEn: ["Patxarán", "Coffee", "Smoke"],
    history: "Una apuesta arriesgada y ahumada que rinde homenaje a las tradiciones del norte con un toque contemporáneo.",
    historyEn: "A bold and smoky bet that pays homage to northern traditions with a contemporary touch.",
    tags: ["Con Alcohol", "Ahumado", "Intenso"],
    tagsEn: ["With Alcohol", "Smoky", "Intense"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771026960/IMG_7104_icekiq.jpg",
    category: "CON ALCOHOL"
  },
  {
    id: "clover-cloud",
    name: "CLOVER CLOUD",
    nameEn: "CLOVER CLOUD",
    price: "15€",
    description: "Gin Malfy, frambuesa, aquafaba.",
    descriptionEn: "Gin Malfy, raspberry, aquafaba.",
    ingredients: ["Gin Malfy", "Frambuesa", "Aquafaba"],
    ingredientsEn: ["Gin Malfy", "Raspberry", "Aquafaba"],
    history: "Textura sedosa y sabor vibrante a frutos rojos en una nube de sabor equilibrado.",
    historyEn: "Silky texture and vibrant red fruit flavor in a cloud of balanced taste.",
    tags: ["Con Alcohol", "Sedoso", "Afrutado"],
    tagsEn: ["With Alcohol", "Silky", "Fruity"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771026960/IMG_7094_dav2tg.jpg",
    category: "CON ALCOHOL"
  },
  {
    id: "mojitos",
    name: "MOJITOS",
    nameEn: "MOJITOS",
    price: "12€",
    description: "Clásico, pasión, fresa o mango.",
    descriptionEn: "Classic, passion fruit, strawberry or mango.",
    ingredients: ["Ron", "Menta", "Lima", "Azúcar", "Soda"],
    ingredientsEn: ["Rum", "Mint", "Lime", "Sugar", "Soda"],
    history: "El alma de Cuba en tu copa. Elige tu sabor favorito y déjate llevar por su frescura inigualable.",
    historyEn: "The soul of Cuba in your glass. Choose your favorite flavor and let yourself be carried away by its unparalleled freshness.",
    tags: ["Con Alcohol", "Tropical", "Personalizable"],
    tagsEn: ["With Alcohol", "Tropical", "Customizable"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771891484/IMG_7475_aryzje.jpg",
    category: "CON ALCOHOL"
  },
  {
    id: "moscow-mule",
    name: "MOSCOW MULE",
    nameEn: "MOSCOW MULE",
    price: "15€",
    description: "Vodka, lima, ginger beer.",
    descriptionEn: "Vodka, lime, ginger beer.",
    ingredients: ["Vodka", "Lima", "Ginger Beer"],
    ingredientsEn: ["Vodka", "Lime", "Ginger Beer"],
    history: "Servido tradicionalmente en taza de cobre, este cóctel es la definición de frescura picante.",
    historyEn: "Traditionally served in a copper mug, this cocktail is the definition of spicy freshness.",
    tags: ["Con Alcohol", "Picante", "Clásico"],
    tagsEn: ["With Alcohol", "Spicy", "Classic"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772187371/moscow_mule_bcrq7n.jpg",
    category: "CON ALCOHOL"
  },
  {
    id: "paloma",
    name: "PALOMA",
    nameEn: "PALOMA",
    price: "15€",
    description: "Tequila, lima, ginger beer.",
    descriptionEn: "Tequila, lime, ginger beer.",
    ingredients: ["Tequila", "Lima", "Ginger Beer"],
    ingredientsEn: ["Tequila", "Lime", "Ginger Beer"],
    history: "Una alternativa refrescante al Margarita que combina la fuerza del tequila con el frescor cítrico.",
    historyEn: "A refreshing alternative to the Margarita that combines the strength of tequila with citric freshness.",
    tags: ["Con Alcohol", "Cítrico", "Tequila"],
    tagsEn: ["With Alcohol", "Citric", "Tequila"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772205827/foto-paloma-comedy-wildlife_qwnbfz.png",
    category: "CON ALCOHOL"
  },
  {
    id: "expresso-martini",
    name: "EXPRESSO MARTINI",
    nameEn: "EXPRESSO MARTINI",
    price: "12€",
    description: "Vodka, licor de café, café.",
    descriptionEn: "Vodka, coffee liqueur, coffee.",
    ingredients: ["Vodka", "Licor de café", "Café"],
    ingredientsEn: ["Vodka", "Coffee liqueur", "Coffee"],
    history: "El cóctel perfecto para los amantes del café que buscan un toque sofisticado y energético.",
    historyEn: "The perfect cocktail for coffee lovers looking for a sophisticated and energetic touch.",
    tags: ["Con Alcohol", "Energético", "Café"],
    tagsEn: ["With Alcohol", "Energetic", "Coffee"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771026961/IMG_7090_lvmezw.jpg",
    category: "CON ALCOHOL"
  },
  {
    id: "negroni",
    name: "NEGRONI",
    nameEn: "NEGRONI",
    price: "11€",
    description: "Martini, Campari, Gin.",
    descriptionEn: "Martini, Campari, Gin.",
    ingredients: ["Martini", "Campari", "Gin"],
    ingredientsEn: ["Martini", "Campari", "Gin"],
    history: "El equilibrio perfecto entre amargor y dulzor, un clásico atemporal nacido en Florencia.",
    historyEn: "The perfect balance between bitterness and sweetness, a timeless classic born in Florence.",
    tags: ["Con Alcohol", "Clásico", "Amargo"],
    tagsEn: ["With Alcohol", "Classic", "Bitter"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772187371/negroni_yl4gsh.jpg",
    category: "CON ALCOHOL"
  },
  {
    id: "margarita",
    name: "MARGARITA",
    nameEn: "MARGARITA",
    price: "12€",
    description: "Tequila, limón, cointreau.",
    descriptionEn: "Tequila, lemon, cointreau.",
    ingredients: ["Tequila", "Limón", "Cointreau"],
    ingredientsEn: ["Tequila", "Lemon", "Cointreau"],
    history: "La esencia de México en una copa, con el toque cítrico perfecto y el borde de sal característico.",
    historyEn: "The essence of Mexico in a glass, with the perfect citric touch and the characteristic salt rim.",
    tags: ["Con Alcohol", "Cítrico", "Clásico"],
    tagsEn: ["With Alcohol", "Citric", "Classic"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772016639/grok-image-be91267f-2216-426b-b108-7e392ca59a6a_ihuq1y.jpg",
    video: "https://res.cloudinary.com/daw44qmzv/video/upload/v1772013505/Mi_pel%C3%ADcula_2_cvgdac.mov",
    category: "CON ALCOHOL"
  },
  {
    id: "destornillador",
    name: "DESTORNILLADOR",
    nameEn: "SCREWDRIVER",
    price: "12€",
    description: "Vodka, refresco de naranja, zumo.",
    descriptionEn: "Vodka, orange soda, juice.",
    ingredients: ["Vodka", "Refresco de naranja", "Zumo de naranja"],
    ingredientsEn: ["Vodka", "Orange soda", "Orange juice"],
    history: "Sencillez y frescura cítrica en un combinado clásico que nunca falla.",
    historyEn: "Simplicity and citric freshness in a classic combination that never fails.",
    tags: ["Con Alcohol", "Cítrico", "Directo"],
    tagsEn: ["With Alcohol", "Citric", "Direct"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772187370/grok-image-423c5849-572f-4595-9e53-c9386c412f0c_yp7d8a.jpg",
    category: "CON ALCOHOL"
  },
  {
    id: "experiment-gt",
    name: "EXPERIMENT G.T.",
    nameEn: "EXPERIMENT G.T.",
    price: "15€",
    description: "Gin & Tonic sorprendente.",
    descriptionEn: "Surprising Gin & Tonic.",
    ingredients: ["Ginebra Premium", "Tónica", "Botánicos secretos"],
    ingredientsEn: ["Premium Gin", "Tonic", "Secret botanicals"],
    history: "Nuestra interpretación del Gin Tonic clásico, elevada con botánicos seleccionados para una experiencia única.",
    historyEn: "Our interpretation of the classic Gin Tonic, elevated with selected botanicals for a unique experience.",
    tags: ["Con Alcohol", "Premium", "Evolucionado"],
    tagsEn: ["With Alcohol", "Premium", "Evolved"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772187370/experiment_gt_k6o6yl.jpg",
    video: "https://res.cloudinary.com/daw44qmzv/video/upload/v1771851357/experiment_gt_vincci_consulado_bilbao_eusfjp.mp4",
    category: "CON ALCOHOL"
  },
  {
    id: "old-fashioned",
    name: "OLD FASHIONED",
    nameEn: "OLD FASHIONED",
    price: "12€",
    description: "Chivas 12, Umeshu, Jengibre.",
    descriptionEn: "Chivas 12, Umeshu, Ginger.",
    ingredients: ["Chivas 12", "Umeshu", "Jengibre"],
    ingredientsEn: ["Chivas 12", "Umeshu", "Ginger"],
    history: "Una vuelta de tuerca al clásico con el toque oriental del Umeshu y el picante del jengibre.",
    historyEn: "A twist on the classic with the oriental touch of Umeshu and the spiciness of ginger.",
    tags: ["Con Alcohol", "Sofisticado", "Fusión"],
    tagsEn: ["With Alcohol", "Sophisticated", "Fusion"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772187371/old_fashioned_w4mbbu.jpg",
    category: "CON ALCOHOL"
  },
  {
    id: "vincci-bull",
    name: "VINCCI BULL",
    nameEn: "VINCCI BULL",
    price: "15€",
    description: "Vodka, fresa, lima, tabasco, red bull.",
    descriptionEn: "Vodka, strawberry, lime, tabasco, red bull.",
    ingredients: ["Vodka", "Fresa", "Lima", "Tabasco", "Red Bull"],
    ingredientsEn: ["Vodka", "Strawberry", "Lime", "Tabasco", "Red Bull"],
    history: "Energía y pasión en una mezcla audaz con un toque picante inesperado.",
    historyEn: "Energy and passion in a bold mix with an unexpected spicy touch.",
    tags: ["Con Alcohol", "Energético", "Atrevido"],
    tagsEn: ["With Alcohol", "Energetic", "Bold"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    category: "CON ALCOHOL"
  },
  {
    id: "citrus-fiero",
    name: "CITRUS FIERO",
    nameEn: "CITRUS FIERO",
    price: "15€",
    description: "Martini fiero, lima, jengibre, tónica.",
    descriptionEn: "Martini fiero, lime, ginger, tonic.",
    ingredients: ["Martini fiero", "Lima", "Jengibre", "Tónica"],
    ingredientsEn: ["Martini fiero", "Lime", "Ginger", "Tonic"],
    history: "Un aperitivo ligero y refrescante con notas cítricas intensas.",
    historyEn: "A light and refreshing aperitif with intense citric notes.",
    tags: ["Low Alcohol", "Cítrico", "Aperitivo"],
    tagsEn: ["Low Alcohol", "Citric", "Aperitif"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771890612/IMG_7098_qpjosq.jpg",
    video: "https://res.cloudinary.com/daw44qmzv/video/upload/v1771754677/202602221033_1_gcqkiw.mp4",
    category: "LOW ALCOHOL"
  },
  {
    id: "bloody-mary",
    name: "BLOODY MARY",
    nameEn: "BLOODY MARY",
    price: "12€",
    description: "Vodka, zumo tomate.",
    descriptionEn: "Vodka, tomato juice.",
    ingredients: ["Vodka", "Zumo de tomate", "Especias"],
    ingredientsEn: ["Vodka", "Tomato juice", "Spices"],
    history: "El clásico reparador, equilibrado y especiado, ideal para cualquier momento del día.",
    historyEn: "The restorative classic, balanced and spicy, ideal for any time of the day.",
    tags: ["Low Alcohol", "Especiado", "Clásico"],
    tagsEn: ["Low Alcohol", "Spicy", "Classic"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772187370/bloody_mary_bkg3vp.jpg",
    category: "LOW ALCOHOL"
  },
  {
    id: "aperol-spritz",
    name: "APEROL SPRITZ",
    nameEn: "APEROL SPRITZ",
    price: "10€",
    description: "Aperol, cava, soda.",
    descriptionEn: "Aperol, cava, soda.",
    ingredients: ["Aperol", "Cava", "Soda"],
    ingredientsEn: ["Aperol", "Cava", "Soda"],
    history: "El rey del aperitivo italiano, vibrante y social.",
    historyEn: "The king of the Italian aperitif, vibrant and social.",
    tags: ["Low Alcohol", "Clásico", "Vibrante"],
    tagsEn: ["Low Alcohol", "Classic", "Vibrant"],
    image: "https://images.unsplash.com/photo-1560512823-829485b8bf24?auto=format&fit=crop&w=800&q=80",
    video: "https://res.cloudinary.com/daw44qmzv/video/upload/v1772013947/Mi_pel%C3%ADcula_3_kr2l0v.mov",
    category: "LOW ALCOHOL"
  },
  {
    id: "valenciano",
    name: "VALENCIANO",
    nameEn: "VALENCIANO",
    price: "11€",
    description: "Helado vainilla, naranja, cointreau.",
    descriptionEn: "Vanilla ice cream, orange, cointreau.",
    ingredients: ["Helado de vainilla", "Zumo de naranja", "Cointreau"],
    ingredientsEn: ["Vanilla ice cream", "Orange juice", "Cointreau"],
    history: "Un postre líquido que combina la cremosidad de la vainilla con el frescor de la naranja valenciana.",
    historyEn: "A liquid dessert that combines the creaminess of vanilla with the freshness of Valencian orange.",
    tags: ["Low Alcohol", "Dulce", "Cremoso"],
    tagsEn: ["Low Alcohol", "Sweet", "Creamy"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772187371/valenciano_gfoxjj.jpg",
    category: "LOW ALCOHOL"
  },
  {
    id: "vibrante-spritz",
    name: "VIBRANTE SPRITZ",
    nameEn: "VIBRANTE SPRITZ",
    price: "11€",
    description: "Martini Vibrante, Maracuyá.",
    descriptionEn: "Martini Vibrante, Passion fruit.",
    ingredients: ["Martini Vibrante", "Maracuyá"],
    ingredientsEn: ["Martini Vibrante", "Passion fruit"],
    history: "Todo el sabor del Spritz sin una gota de alcohol. Vibrante y exótico.",
    historyEn: "All the flavor of the Spritz without a drop of alcohol. Vibrant and exotic.",
    tags: ["Sin Alcohol", "Exótico", "Ligero"],
    tagsEn: ["Alcohol Free", "Exotic", "Light"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772187375/vibrante_red43a.jpg",
    category: "SIN ALCOHOL"
  },
  {
    id: "floreale-spritz",
    name: "FLOREALE SPRITZ",
    nameEn: "FLOREALE SPRITZ",
    price: "11€",
    description: "Martini Floreale, Vainilla.",
    descriptionEn: "Martini Floreale, Vanilla.",
    ingredients: ["Martini Floreale", "Vainilla"],
    ingredientsEn: ["Martini Floreale", "Vanilla"],
    history: "Notas florales y un toque de vainilla para un brindis sin alcohol.",
    historyEn: "Floral notes and a touch of vanilla for an alcohol-free toast.",
    tags: ["Sin Alcohol", "Floral", "Elegante"],
    tagsEn: ["Alcohol Free", "Floral", "Elegant"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772187371/floreale_le5hyl.jpg",
    category: "SIN ALCOHOL"
  },
  {
    id: "sanfran",
    name: "SANFRAN",
    nameEn: "SANFRAN",
    price: "10€",
    description: "Mix de zumos, granadina.",
    descriptionEn: "Juice mix, grenadine.",
    ingredients: ["Naranja", "Piña", "Melocotón", "Granadina"],
    ingredientsEn: ["Orange", "Pineapple", "Peach", "Grenadine"],
    history: "El cóctel sin alcohol por excelencia, una explosión de frutas tropicales y color.",
    historyEn: "The ultimate alcohol-free cocktail, an explosion of tropical fruits and color.",
    tags: ["Sin Alcohol", "Frutal", "Clásico"],
    tagsEn: ["Alcohol Free", "Fruity", "Classic"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1772187801/sanfran_jje9jw.jpg",
    category: "SIN ALCOHOL"
  }
];

export const SNACKS: MenuItem[] = [
  {
    id: "jamon-iberico",
    name: "Plato de Jamón con pa amb tomàquet",
    nameEn: "Iberian Ham with Bread and Tomato",
    price: "28,00€",
    description: "Iberian ham with bread and tomato",
    descriptionEn: "Iberian ham with bread and tomato",
    history: "Selección de jamón ibérico de bellota acompañado del tradicional pan con tomate catalán.",
    historyEn: "Selection of acorn-fed Iberian ham accompanied by traditional Catalan bread with tomato.",
    tags: ["Clásico", "Ibérico"],
    tagsEn: ["Classic", "Iberian"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771060219/como-colocar-un-jamon-1_e1eab6.jpg",
    video: "https://res.cloudinary.com/daw44qmzv/video/upload/v1771670845/poboy_langostinos_i4tegv.mp4"
  },
  {
    id: "tabla-quesos",
    name: "Tabla de quesos",
    nameEn: "Cheese Board",
    price: "19,00€",
    description: "Cheese board",
    descriptionEn: "Cheese board",
    history: "Una cuidada selección de quesos nacionales e internacionales, acompañados de frutos secos y mermeladas artesanas.",
    historyEn: "A careful selection of national and international cheeses, accompanied by nuts and artisan jams.",
    tags: ["Quesos", "Compartir"],
    tagsEn: ["Cheese", "Share"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771060479/IMG_7386_z5mhcz.jpg"
  },
  {
    id: "pulpo-plancha",
    name: "Pulpo a la plancha con patata y mahonesa al pimentón",
    nameEn: "Grilled Octopus with Potato and Paprika Mayonnaise",
    price: "20,00€",
    description: "Grilled octopus with tomato and paprika mayonnaise",
    descriptionEn: "Grilled octopus with tomato and paprika mayonnaise",
    history: "Pulpo gallego braseado con una base de patata confitada y el toque ahumado del pimentón de la Vera.",
    historyEn: "Braised Galician octopus with a base of confit potato and the smoky touch of paprika from La Vera.",
    tags: ["Mar", "Gourmet"],
    tagsEn: ["Sea", "Gourmet"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771059539/0000_pata-de-pulpo-plancha-con-pure-de-patata-ahumado_hpllmu.png"
  },
  {
    id: "langostinos-rebozados",
    name: "Langostinos rebozados",
    nameEn: "Breaded Shrimp",
    price: "12,00€",
    description: "Breaded shrimp",
    descriptionEn: "Breaded shrimp",
    history: "Crujientes langostinos con un rebozado ligero y dorado, ideales para abrir el apetito.",
    historyEn: "Crunchy shrimp with a light and golden breading, ideal for whetting the appetite.",
    tags: ["Crujiente", "Mar"],
    tagsEn: ["Crunchy", "Sea"],
    image: "https://res.cloudinary.com/daw44qmzv/image/upload/v1771060078/IMG_7385_culth0.jpg",
    video: "https://res.cloudinary.com/daw44qmzv/video/upload/v1771318103/grok-video-200d18b2-dbb1-40c9-b4a8-9c452c6a91d3_ieecev.mp4"
  },
  {
    id: "rabas",
    name: "Rabas",
    nameEn: "Fried Squid Rings",
    price: "12,00€",
    description: "Rabas of calamary",
    descriptionEn: "Squid rings",
    history: "Tiras de calamar fresco fritas al estilo tradicional, tiernas por dentro y crujientes por fuera.",
    historyEn: "Fresh squid strips fried in the traditional style, tender on the inside and crunchy on the outside.",
    tags: ["Clásico", "Mar"],
    tagsEn: ["Classic", "Sea"],
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "presa-cerdo",
    name: "Presa de cerdo con patatas fritas",
    nameEn: "Pork 'Presa' with French Fries",
    price: "16,00€",
    description: "Pork ”Presa” with French Fries",
    descriptionEn: "Pork 'Presa' with French Fries",
    history: "Corte noble de cerdo ibérico cocinado en su punto, acompañado de patatas caseras.",
    historyEn: "Noble cut of Iberian pork cooked to perfection, accompanied by homemade potatoes.",
    tags: ["Carne", "Ibérico"],
    tagsEn: ["Meat", "Iberian"],
    image: "https://images.unsplash.com/photo-1603048297172-c92544798d5e?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "ensalada-ventresca",
    name: "Ensalada de Ventresca con Antxoas",
    nameEn: "Tuna Belly and Anchovy Salad",
    price: "14,00€",
    description: "Tuna belly and anchovy salad",
    descriptionEn: "Tuna belly and anchovy salad",
    history: "La frescura de la ventresca de atún premium combinada con la intensidad de las anchoas del Cantábrico.",
    historyEn: "The freshness of premium tuna belly combined with the intensity of Cantabrian anchovies.",
    tags: ["Fresco", "Mar"],
    tagsEn: ["Fresh", "Sea"],
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "ensaladilla-rusa",
    name: "Ensaladilla rusa casera",
    nameEn: "Homemade Russian Salad",
    price: "12,00€",
    description: "Homemade Olivier salad",
    descriptionEn: "Homemade Russian salad",
    history: "Nuestra receta secreta, cremosa y equilibrada, un imprescindible de nuestra barra.",
    historyEn: "Our secret recipe, creamy and balanced, a must-have at our bar.",
    tags: ["Clásico", "Casero"],
    tagsEn: ["Classic", "Homemade"],
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "crudite-verduras",
    name: "Crudité de verduras con guacamole y hummus",
    nameEn: "Vegetable Crudités with Guacamole and Hummus",
    price: "11,00€",
    description: "Crudités with Guacamole and Hummus",
    descriptionEn: "Crudités with Guacamole and Hummus",
    history: "Opción saludable y refrescante con verduras de temporada y nuestros dips caseros.",
    historyEn: "Healthy and refreshing option with seasonal vegetables and our homemade dips.",
    tags: ["Saludable", "Vegetariano"],
    tagsEn: ["Healthy", "Vegetarian"],
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "corazones-alcachofas",
    name: "Corazones de alcachofas en escabeche",
    nameEn: "Marinated Artichoke Hearts",
    price: "14,00€",
    description: "Marinated artichoke hearts",
    descriptionEn: "Marinated artichoke hearts",
    history: "Alcachofas seleccionadas con un escabeche suave que realza su sabor natural.",
    historyEn: "Selected artichokes with a mild marinade that enhances their natural flavor.",
    tags: ["Gourmet", "Vegetal"],
    tagsEn: ["Gourmet", "Vegetable"],
    image: "https://images.unsplash.com/photo-1515471204579-f30b04a38921?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "gyozas-verduras",
    name: "Gyozas de verduras y emulsión de Syracha",
    nameEn: "Vegetable Gyozas with Sriracha Emulsion",
    price: "9,00€",
    description: "Vegetable gyozas with a mild Sriracha emulsion",
    descriptionEn: "Vegetable gyozas with a mild Sriracha emulsion",
    history: "Fusión oriental con un toque picante sutil que despierta los sentidos.",
    historyEn: "Oriental fusion with a subtle spicy touch that awakens the senses.",
    tags: ["Fusión", "Picante"],
    tagsEn: ["Fusion", "Spicy"],
    image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "croquetas-jamon",
    name: "Croquetas caseras de jamón",
    nameEn: "Homemade Ham Croquettes",
    price: "12,00€",
    description: "Homemade croquettes",
    descriptionEn: "Homemade ham croquettes",
    history: "Receta tradicional de la abuela, con bechamel cremosa y trocitos de jamón ibérico.",
    historyEn: "Traditional grandmother's recipe, with creamy bechamel and pieces of Iberian ham.",
    tags: ["Casero", "Imprescindible"],
    tagsEn: ["Homemade", "Must-have"],
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "patatas-dos-cocciones",
    name: "Patatas en dos cocciones con salsa de queso y sal de jamón",
    nameEn: "Double-Cooked Potatoes with Cheese Sauce and Ham Salt",
    price: "11,00€",
    description: "Homemade spicy potatoes",
    descriptionEn: "Homemade spicy potatoes",
    history: "Nuestra versión de las bravas: crujientes por fuera, fundentes por dentro y con un toque de jamón.",
    historyEn: "Our version of 'bravas': crunchy on the outside, melting on the inside and with a touch of ham.",
    tags: ["Clásico", "Favorito"],
    tagsEn: ["Classic", "Favorite"],
    image: "https://images.unsplash.com/photo-1518013031914-e0b7c522ffb6?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "tarta-queso",
    name: "Tarta de queso Idiazábal",
    nameEn: "Idiazabal Cheesecake",
    price: "6,50€",
    description: "Idiazábal cheese cake",
    descriptionEn: "Idiazabal cheesecake",
    history: "Cremosa y con el carácter inconfundible del queso Idiazábal ahumado.",
    historyEn: "Creamy and with the unmistakable character of smoked Idiazabal cheese.",
    tags: ["Postre", "Queso"],
    tagsEn: ["Dessert", "Cheese"],
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "tarta-sacher",
    name: "Tarta Sacher de chocolate",
    nameEn: "Chocolate Sacher Cake",
    price: "7,00€",
    description: "Chocolate Sacher cake",
    descriptionEn: "Chocolate Sacher cake",
    history: "Para los amantes del chocolate: bizcocho denso, mermelada de albaricoque y cobertura brillante.",
    historyEn: "For chocolate lovers: dense sponge cake, apricot jam and shiny coating.",
    tags: ["Postre", "Chocolate"],
    tagsEn: ["Dessert", "Chocolate"],
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "copa-helado",
    name: "Copa de Helado",
    nameEn: "Ice Cream Cup",
    price: "6,50€",
    description: "Ice Cream",
    descriptionEn: "Ice cream",
    history: "Selección de nuestros mejores helados artesanos, el final perfecto y refrescante.",
    historyEn: "Selection of our best artisan ice creams, the perfect and refreshing finale.",
    tags: ["Postre", "Frío"],
    tagsEn: ["Dessert", "Cold"],
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "postre-chef",
    name: "Postre del chef + 2½ Gin Tonic",
    nameEn: "Chef's Dessert + 2½ Gin & Tonic",
    price: "18,00€",
    description: "Chef’s dessert + 2½ Gin & Tonic",
    descriptionEn: "Chef's dessert + 2½ Gin & Tonic",
    history: "La combinación definitiva: el postre especial del día maridado con nuestro Gin Tonic de autor.",
    historyEn: "The ultimate combination: the special dessert of the day paired with our signature Gin Tonic.",
    tags: ["Gourmet", "Experiencia"],
    tagsEn: ["Gourmet", "Experience"],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80"
  }
];

export const RESTO_BEBIDAS: DrinkCategory[] = [
  {
    name: "CAFETERÍA TEA & COFFEE",
    nameEn: "TEA & COFFEE SHOP",
    items: [
      { id: "infusion", name: "Infusiones premium Premium tea", nameEn: "Premium Tea", price: "3,75€" },
      { id: "bombon", name: "Café Bombón Coffee with condensed milk", nameEn: "Coffee with Condensed Milk", price: "4,00€" },
      { id: "carajillo", name: "Café Carajillo Nespresso Nespresso black coffee with a shot of brandy", nameEn: "Nespresso Coffee with Brandy", price: "4,75€" },
      { id: "espresso", name: "Café Nespresso Nespresso coffee", nameEn: "Nespresso Coffee", price: "3,50€" },
      { id: "capuccino", name: "Capuccino Nespresso Nespresso cappuccino", nameEn: "Nespresso Cappuccino", price: "3,75€" },
      { id: "cafe-leche", name: "Café con leche White coffee", nameEn: "Coffee with Milk", price: "3,70€" },
      { id: "latte", name: "Latte Macchiato Latte macchiato", nameEn: "Latte Macchiato", price: "3,75€" },
      { id: "chocolate", name: "Chocolate Hot chocolate", nameEn: "Hot Chocolate", price: "3,50€" },
      { id: "colacao", name: "Cola Cao Cola Cao hot chocolate drink", nameEn: "Cola Cao", price: "3,50€" },
      { id: "zumo-melocoton", name: "Zumo Melocotón Peach juice", nameEn: "Peach Juice", price: "3,25€" },
      { id: "zumo-naranja", name: "Zumo Naranja Orange juice", nameEn: "Orange Juice", price: "3,25€" },
      { id: "zumo-pina", name: "Zumo Piña Vida Pineapple juice", nameEn: "Pineapple Juice", price: "3,25€" },
      { id: "zumo-tomate", name: "Zumo Tomate Vida Tomato juice", nameEn: "Tomato Juice", price: "3,25€" },
      { id: "zumo-natural", name: "Zumo Naranja Natural Natural orange juice", nameEn: "Fresh Orange Juice", price: "4,50€" }
    ]
  },
  {
    name: "REFRESCOS Y AGUA SOFT DRINKS AND WATER",
    nameEn: "SOFT DRINKS AND WATER",
    items: [
      { id: "agua-1l", name: "Agua Culligan 1L Culligan water 1L bottle", nameEn: "Culligan Water 1L", price: "3,50€" },
      { id: "agua-05l", name: "Agua Culligan 0,5 L Culligan water 0.5L bottle", nameEn: "Culligan Water 0.5L", price: "2,75€" },
      { id: "coca-cola-zero", name: "Coca Cola Zero", nameEn: "Coca Cola Zero", price: "3,50€" },
      { id: "coca-cola", name: "Coca Cola", nameEn: "Coca Cola", price: "3,50€" },
      { id: "schweppes-limon", name: "Schweppes Limón Schweppes sparkling lemon", nameEn: "Schweppes Lemon", price: "3,50€" },
      { id: "schweppes-naranja", name: "Schweppes Naranja Schweppes sparkling orange", nameEn: "Schweppes Orange", price: "3,50€" },
      { id: "schweppes-lima", name: "Schweppes Tónica Lima Schweppes lime tonic water", nameEn: "Schweppes Lime Tonic", price: "5,50€" },
      { id: "schweppes-tonica", name: "Schweppes Tónica Schweppes tonic water", nameEn: "Schweppes Tonic", price: "3,50€" },
      { id: "aquarius", name: "Aquarius", nameEn: "Aquarius", price: "3,50€" },
      { id: "fuzetea", name: "Fuzetea", nameEn: "Fuzetea", price: "3,50€" },
      { id: "red-bull", name: "Red Bull Lata Red Bull can", nameEn: "Red Bull Can", price: "4,50€" },
      { id: "cana", name: "Caña Small draft beer", nameEn: "Small Draft Beer", price: "3,50€" },
      { id: "pinta", name: "Pinta Pint of draft beer", nameEn: "Pint of Draft Beer", price: "4,50€" },
      { id: "clara", name: "Cerveza Clara de limón Shandy with lemonade", nameEn: "Shandy", price: "3,50€" },
      { id: "estrella-1906", name: "Cerveza Estrella Galicia 1906 33cl Estrella Galicia 1906 beer 33cl bottle", nameEn: "Estrella Galicia 1906 33cl", price: "4,00€" },
      { id: "mahou-33", name: "Cerveza Mahou 33cl Mahou beer 33cl bottle", nameEn: "Mahou Beer 33cl", price: "3,75€" },
      { id: "la-salve", name: "Cerveza La Salve Especial La Salve special-edition beer", nameEn: "La Salve Special Beer", price: "4,00€" },
      { id: "mahou-sin", name: "Mahou Sin alcohol 33cl Alcohol-free Mahou beer 33cl bottle", nameEn: "Alcohol-free Mahou 33cl", price: "3,50€" },
      { id: "mahou-gluten", name: "Mahou Sin gluten 33cl Ret Gluten-free Mahou beer 33cl bottle", nameEn: "Gluten-free Mahou 33cl", price: "4,00€" },
      { id: "vino-blanco", name: "Copa de Vino Blanco Glass of white wine", nameEn: "Glass of White Wine", price: "3,50€" },
      { id: "vino-tinto", name: "Copa de Vino Tinto Glass of red wine", nameEn: "Glass of Red Wine", price: "3,50€" },
      { id: "kalimotxo", name: "Kalimotxo Coke & wine", nameEn: "Kalimotxo", price: "6,00€" }
    ]
  },
  {
    name: "COMBINADOS MIXED DRINKS",
    nameEn: "MIXED DRINKS",
    items: [
      { id: "bacardi-8", name: "Ron Bacardi 8 Años Bacardi 8 Años rum", nameEn: "Bacardi 8 Years Rum", price: "12,00€" },
      { id: "bacardi-carta", name: "Ron Bacardi Carta Blanca Bacardi Carta Blanca rum", nameEn: "Bacardi White Rum", price: "10,00€" },
      { id: "brugal", name: "Ron Brugal Añejo Brugal Añejo rum", nameEn: "Brugal Aged Rum", price: "10,00€" },
      { id: "cacique", name: "Ron Cacique 500 Cacique 500 rum", nameEn: "Cacique 500 Rum", price: "11,00€" },
      { id: "havana-7", name: "Ron Havana 7 Años Havana 7 Años rum", nameEn: "Havana 7 Years Rum", price: "10,00€" },
      { id: "chupito-sauza", name: "Chupito Tequila Sauza Shot of Sauza tequila", nameEn: "Sauza Tequila Shot", price: "5,25€" },
      { id: "cuervo-anejo", name: "Tequila Cuervo Añejo Cuervo Añejo tequila", nameEn: "Cuervo Aged Tequila", price: "6,25€" },
      { id: "sauza-blanco", name: "Tequila Sauza Blanco Sauza Silver tequila", nameEn: "Sauza Silver Tequila", price: "9,00€" },
      { id: "chupito-absolut", name: "Chupito Vodka Absolut Azul Shot of Absolut Blue vodka", nameEn: "Absolut Vodka Shot", price: "6,25€" },
      { id: "vodka-absolut", name: "Vodka Absolut Absolut Vodka", nameEn: "Absolut Vodka", price: "10,00€" },
      { id: "vodka-beluga", name: "Vodka Beluga Beluga vodka", nameEn: "Beluga Vodka", price: "14,00€" },
      { id: "absolut-elyxir", name: "Vodka Absolut Elyxir", nameEn: "Absolut Elyxir Vodka", price: "15,00€" },
      { id: "moskovkaya", name: "Vodka Moskovkaya Moskovskaya vodka", nameEn: "Moskovskaya Vodka", price: "10,00€" },
      { id: "beefeater", name: "Ginebra Beefeater Beefeater gin", nameEn: "Beefeater Gin", price: "10,00€" },
      { id: "bombay-orig", name: "Ginebra Bombay Original Bombay Original gin", nameEn: "Bombay Original Gin", price: "10,00€" },
      { id: "bombay-sapph", name: "Ginebra Bombay Sapphire Bombay Sapphire gin", nameEn: "Bombay Sapphire Gin", price: "12,00€" },
      { id: "bulldog", name: "Ginebra Bulldog Bulldog gin", nameEn: "Bulldog Gin", price: "13,00€" },
      { id: "citadelle", name: "Ginebra Citadelle Citadelle gin", nameEn: "Citadelle Gin", price: "13,00€" },
      { id: "london-gin", name: "Ginebra London Gin London gin", nameEn: "London Gin", price: "13,00€" },
      { id: "martin-miller", name: "Ginebra Martin Miller Martin Miller gin", nameEn: "Martin Miller Gin", price: "13,00€" },
      { id: "seagrams", name: "Ginebra Seagrams Seagrams gin", nameEn: "Seagrams Gin", price: "10,00€" },
      { id: "tanqueray", name: "Ginebra Tanqueray Tanqueray gin", nameEn: "Tanqueray Gin", price: "10,00€" },
      { id: "malfy-limone", name: "Ginebra Malfy Limone", nameEn: "Malfy Lemon Gin", price: "11,00€" },
      { id: "ballantines", name: "Whisky Ballantines Ballantines whisky", nameEn: "Ballantines Whisky", price: "10,00€" },
      { id: "chivas-12", name: "Whisky Chivas Regal 12 Años Chivas Regal Aged 12 Years whisky", nameEn: "Chivas Regal 12 Years Whisky", price: "16,00€" },
      { id: "chivas-mizunara", name: "Whisky Chivas Mizunara", nameEn: "Chivas Mizunara Whisky", price: "16,00€" },
      { id: "cutty-sark", name: "Whisky Cutty Sark Cutty Sark whisky", nameEn: "Cutty Sark Whisky", price: "10,00€" },
      { id: "dewars-white", name: "Whisky Dewar´S White Label Dewar's White Label whisky", nameEn: "Dewar's White Label Whisky", price: "10,00€" },
      { id: "dewars-caribbean", name: "Whisky Dewar’s Caribbean Smooth", nameEn: "Dewar's Caribbean Smooth Whisky", price: "12,00€" },
      { id: "glen-rothes", name: "Whisky Glen Rothes Glen Rothes whisky", nameEn: "Glen Rothes Whisky", price: "16,00€" },
      { id: "glenfiddich-12", name: "Whisky Glenfiddich 12 Años Glenfiddich 12 Years whisky", nameEn: "Glenfiddich 12 Years Whisky", price: "16,00€" },
      { id: "jb", name: "Whisky J&B J&B whisky", nameEn: "J&B Whisky", price: "10,00€" },
      { id: "jack-daniels", name: "Whisky Jack Daniels Jack Daniels whiskey", nameEn: "Jack Daniels Whiskey", price: "12,00€" },
      { id: "jameson", name: "Whisky Jameson Jameson whiskey", nameEn: "Jameson Whiskey", price: "12,00€" },
      { id: "johnnie-black", name: "Whisky Johnnie Walker Black Johnnie Walker Black whisky", nameEn: "Johnnie Walker Black Whisky", price: "16,00€" },
      { id: "knockando-12", name: "Whisky Knockando 12 Años Knockando Aged 12 Years whisky", nameEn: "Knockando 12 Years Whisky", price: "16,00€" },
      { id: "macallan", name: "Whisky Macallan Macallan whisky", nameEn: "Macallan Whisky", price: "18,00€" }
    ]
  },
  {
    name: "LICORES Y APERITIVOS LIQUEURS AND APERITIFS",
    nameEn: "LIQUEURS AND APERITIFS",
    items: [
      { id: "martini-ambrato", name: "Aperitivo Martini Reserva Speciale Ambrato", nameEn: "Martini Reserva Speciale Ambrato", price: "6,25€" },
      { id: "martini-rubino", name: "Aperitivo Martini Reserva Speciale Rubino", nameEn: "Martini Reserva Speciale Rubino", price: "6,25€" },
      { id: "martini-bianco", name: "Aperitivo Martini Bianco Martini Bianco aperitif", nameEn: "Martini Bianco", price: "5,25€" },
      { id: "martini-dry", name: "Aperitivo Martini Bianco Dry Martini Bianco Dry aperitif", nameEn: "Martini Extra Dry", price: "5,25€" },
      { id: "martini-rosso", name: "Aperitivo Martini Rosso/Rosato Martini Rosso/Rosato aperitif", nameEn: "Martini Rosso/Rosato", price: "5,25€" },
      { id: "baileys", name: "Licor Baileys Baileys Irish Cream liqueur", nameEn: "Baileys Irish Cream", price: "5,25€" },
      { id: "cointreau", name: "Licor Cointreau Cointreau liqueur", nameEn: "Cointreau Liqueur", price: "5,25€" },
      { id: "hierbas-ruavieja", name: "Licor De Hierbas Ruavieja 0,7 Ruavieja herb liqueur 0.7L", nameEn: "Ruavieja Herb Liqueur", price: "5,25€" },
      { id: "frangelico", name: "Licor Frangelico Frangelico liqueur", nameEn: "Frangelico Liqueur", price: "5,25€" },
      { id: "granpecher", name: "Licor Granpecher Melocoton 0,7 Granpecher peach liquear 0.7L", nameEn: "Granpecher Peach Liqueur", price: "5,25€" },
      { id: "granpomier", name: "Licor Granpomier Manzana Verde Granpomier green apple liqueur", nameEn: "Granpomier Green Apple Liqueur", price: "5,25€" },
      { id: "malibu", name: "Licor Malibu Malibu liqueur", nameEn: "Malibu Liqueur", price: "4€" },
      { id: "ruavieja-orujo", name: "Licor Ruavieja Orujo Ruavieja eau-de-vie", nameEn: "Ruavieja Orujo Liqueur", price: "5,25€" },
      { id: "chupito-hierbas", name: "Chupito Licor De Hierbas Ruavi Shot of Ruavieja herb liqueur", nameEn: "Herb Liqueur Shot", price: "3,25€" },
      { id: "chupito-granpecher", name: "Chupito Licor Granpecher Meloc Shot of Granpecher peach liqueur", nameEn: "Peach Liqueur Shot", price: "3,25€" },
      { id: "chupito-granpomier", name: "Chupito Licor Granpomier Manza Shot of Granpomier apple liqueur", nameEn: "Apple Liqueur Shot", price: "3,25€" },
      { id: "chupito-orujo", name: "Chupito Licor Ruavieja Orujo Shot of Ruavieja eau-de-vie", nameEn: "Orujo Shot", price: "3,25€" }
    ]
  }
];

export const PAIRING_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    recommendation: {
      type: Type.STRING,
      description: "A short, enticing recommendation for a pairing.",
    },
    reason: {
      type: Type.STRING,
      description: "The culinary or mixological reason why this pairing works.",
    },
    suggestedItem: {
      type: Type.STRING,
      description: "The name of the suggested item from the other list.",
    }
  },
  required: ["recommendation", "reason", "suggestedItem"],
};
